name: Database Discovery

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MYSQL_HOST: tdupoiron-mysql.mysql.database.azure.com
  MYSQL_DATABASE: flexibleserverdb
  MYSQL_USER: mysqladmin

jobs:
  discover:
    runs-on: tdupoiron-vnet-runner

    steps:
      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: List Databases
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                -e "SHOW DATABASES;"

      - name: List Tables in flexibleserverdb
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                ${{ env.MYSQL_DATABASE }} \
                -e "SHOW TABLES;"

      - name: Show Table Schemas
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                ${{ env.MYSQL_DATABASE }} \
                -e "SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
                    FROM INFORMATION_SCHEMA.COLUMNS 
                    WHERE TABLE_SCHEMA = '${{ env.MYSQL_DATABASE }}' 
                    ORDER BY TABLE_NAME, ORDINAL_POSITION;"
