name: Create Books Table

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      title:
        description: 'Book title'
        required: true
        type: string
      author:
        description: 'Book author'
        required: true
        type: string
      publication_year:
        description: 'Publication year'
        required: true
        type: number

env:
  MYSQL_HOST: tdupoiron-mysql-cap.mysql.database.azure.com
  MYSQL_DATABASE: flexibleserverdb
  MYSQL_USER: mysqladmin

jobs:
  create-table:
    runs-on: tdupoiron-demo-vnet-runner-cap

    steps:
      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Create Books Table
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                ${{ env.MYSQL_DATABASE }} \
                -e "CREATE TABLE IF NOT EXISTS books (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    author VARCHAR(255) NOT NULL,
                    publication_year INT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );"

      - name: Insert Book
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                ${{ env.MYSQL_DATABASE }} \
                -e "INSERT INTO books (title, author, publication_year) 
                    VALUES ('${{ inputs.title }}', '${{ inputs.author }}', ${{ inputs.publication_year }});"

      - name: Verify Table Creation and Data
        run: |
          mysql --host=${{ env.MYSQL_HOST }} \
                --user=${{ env.MYSQL_USER }} \
                --password=${{ secrets.MYSQL_PASSWORD }} \
                ${{ env.MYSQL_DATABASE }} \
                -e "SELECT * FROM books;"
