name: MySQL Discover Tables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job to discover MySQL tables
  discover-mysql-tables:
    # The type of runner that the job will run on
    runs-on: tdupoiron-vnet-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Install MySQL client if it's not already installed
      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
      
      # Run the MySQL command to discover tables
      - name: List MySQL Tables
        run: mysql -h tdupoiron-mysql.mysql.database.azure.com -u mysqladmin -pMySecurePassword123 -D flexibleserverdb -e "SHOW TABLES;"